name: Ci Job

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  review-and-test:
    name: lint / tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        version: [ 16 ]
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
            node-version: ${{ matrix.version }}
            registry-url: 'https://registry.npmjs.org'
            cache: "yarn"
      - name: "Yarn Install"
        run: "yarn"
      - if: ${{ github.event_name == 'pull_request' }}
        name: "Review Dog Pull Request"
        uses: "reviewdog/action-eslint@v1"
        with:
            reporter: github-check
            github_token: ${{ secrets.GH_TOKEN }}
            eslint_flags: "."
            fail_on_error: true
      - name: "Run Tests"
        run: "yarn test:ci"
      - name: "Build Code"
        run: "yarn build"
      - if: ${{ github.event_name == 'push' && $isPackage }}
        run: "yarn semantic-release"
        env:
          isPackage: ${{ secrets.IS_PACKAGE }}
